/*
 * Sean Fischer
 * 9/24/2019
 *
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ..
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#define TARGET_N 500
#define TRUE 1
#define FALSE 0

long nth_tri_num(long n) { return n * (n + 1) / 2; }

int n_divisors(long n) {
  // Try brute force first
  long n_div = 1;
  for (int i = 2; i < sqrt(n); i++) {
    if (n % i == 0) {
      n_div += 2;
    }
  }
  return n_div;
}

int main(int argc, char *argv[]) {

  int d;
  long p;
  long n = 1;
  do {
    p = nth_tri_num(n);
    d = n_divisors(p);
    n++;
  } while (d < TARGET_N);
  printf("%li, %d\n", p, d);

  return 0;
}
