/*
 * Sean Fischer
 * 9/17/2019
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

#define UPPER_THRESH 4000000
#define SEQ_START_A 1
#define SEQ_START_B 2

int main(int argc, char *argv[]) {
  // For some reason this sequence is starting with (1,2) instead
  // of the traditional (0,1)
  // We are using unisgned long itns because it is the smalles int type
  // which is able to hold the integers we are working with.
  // We use the unsigned variant becuase we are guaranteeing no negative n's
  unsigned long running_sum = 0;
  unsigned long a = SEQ_START_A;
  unsigned long b = SEQ_START_B;
  unsigned long tmp;
  while (b < UPPER_THRESH) {
    if (b % 2 == 0) {
      running_sum += b;
    }
    tmp = b;
    b = a + b;
    a = tmp;
  }

  printf("%li\n", running_sum);

  return 0;
}